# Install by OS family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# Check version and service state
- block:
  - name: Check Passenger Version
    shell: sudo sh -c "passenger -v 1>> /data/logs/install_version.txt"

  - name: Check Passgener Service
    shell: /usr/sbin/passenger-memory-stats | grep watchdog
    register: check_passenger_service
    notify: check_passenger_service
